# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "http://www.google.com:8080"
      test_command='curl \
          -w "%{http_code}\\n" \
          "http://www.google.com:8080/" \
          -o /dev/null \
          --connect-timeout 3 \
          --max-time 5'
      if [ $(test_command) == "200" ] ; 
      then
         echo "OK" ;
      else
         echo "KO" ;
      fi

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "http://www.google.com"
      test_command='curl \
          -w "%{http_code}\\n" \
          "http://www.google.com" \
          -o /dev/null \
          --connect-timeout 3 \
          --max-time 5'
      if [ $(test_command) == "200" ] ; 
      then
         echo "OK" ;
      else
         echo "KO" ;
      fi

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "http://www.microsoft.com"
      test_command='curl \
          -w "%{http_code}\\n" \
          "http://www.microsoft.com" \
          -o /dev/null \
          --connect-timeout 3 \
          --max-time 5'
      if [ $(test_command) == "200" ] ; 
      then
         echo "OK" ;
      else
         echo "KO" ;
      fi

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'